### ISSUE TITLE
temp directories may be deleted by child processes

### ISSUE THREAD

**Issue by skaji** [dagolden/File-pushd#12]
Currently directories created by File::pushd::tempd may be deleted by child processes.
```perl
# test.pl
use strict;
use warnings;
use File::pushd;
use Cwd 'getcwd';

my $tempd = tempd;

my $pid = fork // die;

if ($pid == 0) {
    exit;
}
wait;

my $cwd = getcwd or die "getcwd: $!";
```
```
❯ perl test.pl
getcwd: No such file or directory at test.pl line 16.
```

I think it would be nice
* a) to delete directories only if `$$` = pid who created the directories, or
* b) to document this behavior in pod clearly.

**Comment by xdg** [comment]
Good catch.  Do you want to write a patch and test to cache and check `$$` in DESTROY?

**Comment by skaji** [comment]
@xdg Thanks!

**Comment by xdg** [comment]
Thank you!  I've released it as a -TRIAL and have a note in my calendar for next week to release stable if it's smoking well.
