### ISSUE TITLE
feature: warn if called in void context

### ISSUE THREAD

**Issue by dolmen** [dagolden/File-pushd#8]
`pushd` is so magic that it is easy to forget to call it in scalar context (as the variable is normally not used in the rest of the scope).
It would be a helpful addition to check if `pushd`/`tempd`/`preserve` are called in void context (`!defined wantarray`) and warn.

**Comment by xdg** [comment]
Great idea.  Want to send a patch? :-)

**Comment by dolmen** [comment]
> Want to send a patch? :-)

Yep.
Ideally the warn would happen only if warnings are enabled in the caller scope. Any idea on how to check that?

**Comment by xdg** [comment]
Probably with `warnings::warn_if()` but you'll need to choose a suitable category.  From `perldiag`, the "useless" warnings appear to be in category "misc".

**Comment by dolmen** [comment]
`"Useless use of %s in void context"` is in the `void` category. That's what I'll use.

**Comment by dolmen** [comment]
Do you have any preference for a module to capture warnings in the testsuite? I can also directly hook `$SIG{__WARN__}` if you prefer...

**Comment by xdg** [comment]
Hook `$SIG{__WARN__}` please.

**Comment by xdg** [comment]
Fixed by #9
